# Generated by Django 5.1.6 on 2025-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('oferecer', 'Ofercer meus serviços'), ('contratar', 'Quero contratar um serviço')], max_length=10),
        ),
    ]
