# Generated by Django 5.1.6 on 2025-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('oferecer', 'Ofercer meus serviços'), ('contratar', 'Quero contratar um serviço'), ('hibrido', 'Quero contratar e oferecer meu serviço')], default='oferecer', max_length=10),
        ),
    ]
